
version: 2.1

orbs:
  android: circleci/android@1.0.3
  codecov: codecov/codecov@1.2.5

jobs:

  build-and-test:
    working_directory: ~/code

    executor:
      name: android/android-machine
      resource-class: large

    steps:
      - checkout

      - android/restore-build-cache
      - android/restore-gradle-cache

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - android/save-build-cache
      - android/save-gradle-cache

      - android/run-tests:
          test-command: ./gradlew jacocoTestReportDebug

      - store_artifacts:
          path: core/build/reports/jacoco/debug/jacoco.xml

      - codecov/upload:
          file: core/build/reports/jacoco/debug/jacoco.xml
          flags: unitTest
          token: CODECOV_TOKEN

      - run:
          name: build apk
          command: |
            ./gradlew build

      - store_artifacts:
         path: app/build/outputs/apk/debug/
         destination: artifact-file

workflows:
  sample:
    jobs:
      - build-and-test
